# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

data:
  study:
    =replace=: true
    source:
      name: Alvarez2022Haaglanden
    split:
      name: SklearnSplit
      split_by: subject
      valid_split_ratio: 0.2
      test_split_ratio: 0.2
      valid_random_state: 33
      test_random_state: 33
    annotate_sleep_onset:
      name: AddSleepOnsetCutTargets
      window_s: 30.0
      lead_s: 300.0
      lag_s: 60.0
      n_eval_windows: 1
      n_train_windows: 20
      seed: 0
