# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

data:
  study:
    source:
      name: Tangermann2012Review
  start: 0.0
brain_model_output_size: &brain_model_output_size 4
metrics: !!python/object/apply:operator.add
  - !!python/object/apply:neuralbench.metric_configs.get_classification_metric_configs
    - *brain_model_output_size
  - - log_name: bal_acc_stream_mean
      name: GroupedMetric
      metric_name: Accuracy
      kwargs: {task: multiclass, num_classes: *brain_model_output_size, average: macro}
      reduction: mean
